# CMake generated Testfile for 
# Source directory: /workspace/lumora
# Build directory: /workspace/lumora/build-dbg
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[roblox_api]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/roblox_api.lua")
set_tests_properties([=[roblox_api]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;99;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[roblox_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/roblox_contract.lua")
set_tests_properties([=[roblox_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;100;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[luau_modern]=] "/workspace/lumora/build-dbg/bin/lumora" "--no-roblox" "/workspace/lumora/tests/luau_modern.lua")
set_tests_properties([=[luau_modern]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;101;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[datatypes_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/datatypes_contract.lua")
set_tests_properties([=[datatypes_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;102;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[properties_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/properties_contract.lua")
set_tests_properties([=[properties_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;103;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[raycast_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/raycast_contract.lua")
set_tests_properties([=[raycast_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;104;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[runservice_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/runservice_contract.lua")
set_tests_properties([=[runservice_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;105;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[events_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/events_contract.lua")
set_tests_properties([=[events_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;106;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[negative_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/negative_contract.lua")
set_tests_properties([=[negative_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;107;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[host_api_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/host_api_contract.lua")
set_tests_properties([=[host_api_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;108;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[simulated_players_esp]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/simulated_players_esp.lua")
set_tests_properties([=[simulated_players_esp]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;109;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[functional_apis_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/functional_apis_contract.lua")
set_tests_properties([=[functional_apis_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;110;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[require_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/require_contract.lua")
set_tests_properties([=[require_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;111;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[require_pure_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "--no-roblox" "/workspace/lumora/tests/require_pure_contract.lua")
set_tests_properties([=[require_pure_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;112;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[lumora_fs_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/lumora_fs_contract.lua")
set_tests_properties([=[lumora_fs_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;113;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[analysis_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/analysis_contract.lua")
set_tests_properties([=[analysis_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;114;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[analysis_cycle_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/analysis_cycle_contract.lua")
set_tests_properties([=[analysis_cycle_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;115;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[standard_modules_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/standard_modules_contract.lua")
set_tests_properties([=[standard_modules_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;116;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[native_modules_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/native_modules_contract.lua")
set_tests_properties([=[native_modules_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;117;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[expanded_native_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/expanded_native_contract.lua")
set_tests_properties([=[expanded_native_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;118;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[introspection_system_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/introspection_system_contract.lua")
set_tests_properties([=[introspection_system_contract]=] PROPERTIES  WORKING_DIRECTORY "/workspace/lumora" _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;119;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[executor_compat_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/executor_compat_contract.lua")
set_tests_properties([=[executor_compat_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;121;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[sandbox_require_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "--sandbox" "/workspace/lumora/tests/sandbox_require_contract.lua")
set_tests_properties([=[sandbox_require_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;122;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[scheduler_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/scheduler_contract.lua")
set_tests_properties([=[scheduler_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;123;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[scheduler_real_contract]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/scheduler_real_contract.lua")
set_tests_properties([=[scheduler_real_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;124;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[attached_library_load]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/examples/attached_library.lua")
set_tests_properties([=[attached_library_load]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;125;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[roblox_parity]=] "/workspace/lumora/build-dbg/bin/lumora" "/workspace/lumora/tests/roblox_parity.lua")
set_tests_properties([=[roblox_parity]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;126;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[native_network_contract]=] "/workspace/lumora/tests/native_network_contract.sh")
set_tests_properties([=[native_network_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;134;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[native_http_server_contract]=] "/workspace/lumora/tests/native_http_server_contract.sh")
set_tests_properties([=[native_http_server_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;135;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[executor_request_contract]=] "/workspace/lumora/tests/executor_request_contract.sh")
set_tests_properties([=[executor_request_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;136;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[smoke]=] "/workspace/lumora/tests/smoke.sh" "/workspace/lumora/build-dbg/bin/lumora")
set_tests_properties([=[smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;138;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[cli_flags]=] "/workspace/lumora/tests/cli_flags.sh" "/workspace/lumora/build-dbg/bin/lumora")
set_tests_properties([=[cli_flags]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;139;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[cli_contract]=] "/workspace/lumora/tests/cli_contract.sh" "/workspace/lumora/build-dbg/bin/lumora")
set_tests_properties([=[cli_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;140;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[sandbox_contract]=] "/workspace/lumora/tests/sandbox_contract.sh" "/workspace/lumora/build-dbg/bin/lumora")
set_tests_properties([=[sandbox_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;141;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[json_schema]=] "/workspace/lumora/tests/json_schema.sh" "/workspace/lumora/build-dbg/bin/lumora")
set_tests_properties([=[json_schema]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;142;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[analyzer_cli]=] "/workspace/lumora/tests/analyzer_cli.sh" "/workspace/lumora/build-dbg/bin/lumora")
set_tests_properties([=[analyzer_cli]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;143;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[differential_contract]=] "/workspace/lumora/tests/differential_contract.sh" "/workspace/lumora/build-dbg/bin/lumora")
set_tests_properties([=[differential_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;144;add_test;/workspace/lumora/CMakeLists.txt;0;")
add_test([=[local_limit_contract]=] "/workspace/lumora/tests/local_limit_contract.sh" "/workspace/lumora/build-dbg/bin/lumora")
set_tests_properties([=[local_limit_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/lumora/CMakeLists.txt;145;add_test;/workspace/lumora/CMakeLists.txt;0;")
subdirs("vendor/luau")
