local regex = require("@lumora/regex")
assert(regex.isMatch("abc-123", "[0-9]+"))
local match = regex.match("abc-123", "([0-9]+)")
assert(match.text == "123" and match.start == 5 and match["groups"][1] == "123")
local all = regex.matchAll("a1 b22", "[0-9]+")
assert(#all == 2 and all[2].text == "22")
assert(regex.replace("a1b2", "[0-9]", "x") == "axbx")
local parts = regex.split("a,b,c", ",")
assert(#parts == 3 and parts[3] == "c")

local analysis = require("@lumora/analysis")
local findings = analysis.scan("local f = loadstring('return 1'); request('x')")
assert(#findings == 2)
local graph = analysis.graph("local function decode() return loadstring('x')() end\nreturn decode()")
assert(graph.lineCount == 2 and #graph.nodes >= 1 and #graph.edges >= 1)

local before = lumora.fs.snapshot()
writefile("fixtures/analysis.txt", "before")
local middle = lumora.fs.snapshot()
writefile("fixtures/analysis.txt", "after")
local after = lumora.fs.snapshot()
local added = lumora.fs.diff(before, middle)
local changed = lumora.fs.diff(middle, after)
assert(#added.added == 1 and added.added[1] == "fixtures/analysis.txt")
assert(#changed.changed == 1 and changed.changed[1] == "fixtures/analysis.txt")

task.clearTrace()
task.spawn(function() task.wait(0.25) end)
task._runScheduler()
local events = task.traceEvents()
assert(#events >= 3)
assert(lumora.capabilities().analysis == true)
print("analysis-contract-ok")
