local luau = require("@lumora/luau")
local system = require("@lumora/system")
local dependency = require("./introspection_dep")
assert(dependency.name == "dependency")
local resolved = luau.resolveModule("./introspection_dep", "tests/introspection_system_contract.lua")
assert(type(resolved) == "string" and resolved:match("introspection_dep%.luau$"), tostring(resolved))
assert(luau.typeofModule("./introspection_dep", "tests/introspection_system_contract.lua") == "table")
assert(type(system.hostname()) == "string" and #system.hostname() > 0)
assert(type(system.tmpdir()) == "string" and #system.tmpdir() > 0)
assert(system.threadCount() >= 1)
assert(#system.cpus() >= 1)
assert(system.uptime() >= 0)
assert(system.totalMemory() > 0 and system.freeMemory() >= 0)
print("introspection-system-contract-ok")
