local fs = require("@lune/fs")
local process = require("@lune/process")
local luau = require("@lune/luau")
assert(type(fs.readFile) == "function")
assert(type(fs.exists) == "function")
assert(type(process.args) == "table")
assert(type(process.cwd) == "function")
assert(type(luau.load) == "function")
local path = "lumora-lune-compat.tmp"
fs.writeFile(path, "embedded-lune")
assert(fs.readFile(path) == "embedded-lune")
assert(fs.exists(path))
fs.remove(path)
assert(not fs.exists(path))
print("lune-compat-ok")
