local crypto = require("@lumora/crypto")
local digest = crypto.digest("sha256", "abc")
assert(#digest == 32)
assert(crypto.base64.decode(crypto.base64.encode("lumora")) == "lumora")
assert(#crypto.randomBytes(16) == 16)
assert(#crypto.hmac("sha256", "key", "message") == 32)

local syntax = require("@lumora/syntax")
local tree = syntax.parse("local x: number = 1 + 2\nreturn x")
assert(tree.complete == true)
assert(tree.nodes > 0)
assert(tree.cstNodes > 0)
assert(#tree.errors == 0)
local bad = syntax.parse("local =")
assert(#bad.errors > 0)

local vm = require("@lumora/vm").create()
assert(vm:eval("return 2 + 3") == 5)
assert(vm:eval("return 'isolated'") == "isolated")
vm:close()

local debugger = require("@lumora/debugger").create()
assert(debugger:setBreakpoint(1) == true)
assert(debugger:start("local a = 1\nreturn a") == false)
local state = debugger:state()
assert(state.started == true and state.hits > 0)
debugger:close()

print("native modules contract ok")
