local a = Path2DControlPoint.new(Vector2.new(1, 2), UDim2.new(0, 3, 0, 4))
local b = Path2DControlPoint.new(Vector2.new(1, 2), UDim2.new(0, 3, 0, 4))
assert(typeof(a) == "Path2DControlPoint")
assert(type(a) == "userdata")
assert(a[1] == Vector2.new(1, 2))
assert(a[2].X.Scale == 0 and a[2].X.Offset == 3)
assert(a[2].Y.Scale == 0 and a[2].Y.Offset == 4)
assert(a == a)
assert(a ~= Path2DControlPoint.new(Vector2.new(9, 9)))
assert(tostring(a) == "Path2DControlPoint(1, 2, {0, 3, 0, 4})")
print("path2d-control-point: ok")
