local p = Instance.new("Part", workspace)
p.Name = "Probe"
assert(p.Parent == workspace)
assert(workspace:FindFirstChild("Probe") == p)
local hit = false
local connection = p.ChildAdded:Connect(function() hit = true end)
Instance.new("Folder", p)
assert(hit and connection.Connected)
connection:Disconnect()
assert(not connection.Connected)
local removed = false
workspace.ChildRemoved:Connect(function(child) removed = child == p end)
p.Parent = game
assert(removed)
assert(workspace:FindFirstChild("Probe") == nil)
assert(typeof(p) == "Instance")
assert(typeof(Vector2.new(1, 2)) == "Vector2")
assert(typeof(UDim2.fromScale(1, 1)) == "UDim2")
assert(typeof(Path2D.new()) == "Path2D")
assert(getmetatable(p) == "The metatable is locked")
assert(Enum.Material.Neon.Name == "Neon")
assert(Enum.Material:FromName("Neon").Name == "Neon")
assert(Enum.Material:FromValue(0).Name == "Neon")
assert(utf8.nfcnormalize("ok") == "ok")
local r = Random.new(7)
assert(r:NextInteger(1, 10) >= 1)
local deferred = false
task.defer(function() deferred = true end)
assert(deferred)
print(p:GetFullName())
