local dt = require("@lune/datetime")
assert(type(dt.now()) == "number")
assert(dt.toUnixTimestamp(dt.fromUnixTimestamp(42)) == 42)
local serde = require("@lune/serde")
local encoded = serde.encode({value = 7})
assert(serde.decode(encoded).value == 7)
assert(type(serde.hash({value = 7})) == "string")
local ui = game:HttpGet("https://example/WindUI")
local window = loadstring(ui)():CreateWindow({})
assert(window:Open() == true and window.IsOpen == true)
local destroyed = false
window:OnDestroy(function() destroyed = true end)
window:Close()
window:Destroy()
assert(destroyed and window.Destroyed)
print("runtime expansion ok")
