local datetime = require("@lumora/datetime")
local serde = require("@lumora/serde")
local standardTask = require("@lumora/task")
local roblox = require("@lumora/roblox")

assert(type(datetime.now) == "function")
local stamp = datetime.now()
assert(type(stamp) == "number")
assert(type(datetime.format(stamp)) == "string")
local encoded = serde.encode({z = 2, a = true})
assert(encoded == '{"a":true,"z":2}', encoded)
local decoded = serde.decode(encoded)
assert(decoded.a == true and decoded.z == 2)
assert(type(standardTask.spawn) == "function")
assert(type(standardTask.wait) == "function")
assert(roblox.Instance == Instance and roblox.Vector3 == Vector3)
print("standard-modules-ok")
