local strings = require("@lumora/stringext")
assert(strings.hasPrefix("lumora", "lum"))
assert(strings.removePrefix("lumora", "lum") == "ora")
assert(strings.hasSuffix("lumora", "ora"))
assert(strings.trim("  lumora  ") == "lumora")
assert(strings.count("a,b,c", ",") == 2)

local tables = require("@lumora/tableext")
assert(tables.any({1, 2, 3}, function(v) return v == 2 end))
assert(tables.all({2, 4}, function(v) return v % 2 == 0 end))
local clone = tables.deepClone({nested = {value = 7}})
assert(clone.nested.value == 7 and clone.nested ~= nil)
assert(tables.mapConcat({"a", "b"}, function(v) return v end, ":") == "a:b")

local time = require("@lumora/time")
local d = time.add(time.seconds(1), time.milliseconds(500))
assert(d.seconds == 1 and d.nanoseconds == 500000000)
assert(time.totalSeconds(time.minutes(2)) == 120)

local system = require("@lumora/system")
assert(type(system.os) == "string")
assert(type(system.arch) == "string")
assert(type(system.cpus()) == "table")
print("stdlib contract ok")
